### ISSUE TITLE
[BUG]1.7.10 Shader Crash

### ISSUE THREAD

**Issue by ENDERMANYK** [PojavLauncherTeam/PojavLauncher#642]
Shader works fine in the 1.12.2 version, but when i switch to 1.7.10 version it crash again. Using the V3.3.1 releases.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 21-1-18 6:05AM
Description: Unexpected error

java.lang.NoSuchMethodError: org.lwjgl.opengl.ARBVertexShader.glVertexAttribPointerARB(IIZZILjava/nio/ShortBuffer;)V
	at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
	at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(Tessellator.java:169)
	at shadersmod.client.Shaders.drawHorizon(Shaders.java:4862)
	at shadersmod.client.Shaders.preSkyList(Shaders.java:4874)
	at net.minecraft.client.renderer.RenderGlobal.func_72714_a(RenderGlobal.java:1731)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1616)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
	at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(Tessellator.java:169)
	at shadersmod.client.Shaders.drawHorizon(Shaders.java:4862)
	at shadersmod.client.Shaders.preSkyList(Shaders.java:4874)
	at net.minecraft.client.renderer.RenderGlobal.func_72714_a(RenderGlobal.java:1731)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1616)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['ENDERMANYK'/503, l='MpServer', x=-30.64, y=78.62, z=47.60]]
	Chunk stats: MultiplayerChunkCache: 426, 614
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (28,64,252), Chunk: (at 12,4,12 in 1,15; contains blocks 16,0,240 to 31,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3536 game time, 3536 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 120 total; [EntitySkeleton['Skeleton'/5134, l='MpServer', x=-68.50, y=15.00, z=34.50], EntityZombie['Zombie'/5136, l='MpServer', x=-46.50, y=43.00, z=24.50], EntityEnderman['Enderman'/5137, l='MpServer', x=-89.59, y=58.00, z=7.53], EntityEnderman['Enderman'/5138, l='MpServer', x=-94.00, y=58.00, z=6.28], EntityPig['Pig'/4115, l='MpServer', x=-106.50, y=75.00, z=37.53], EntityEnderman['Enderman'/5139, l='MpServer', x=-91.50, y=58.00, z=4.50], EntityPig['Pig'/4116, l='MpServer', x=-106.50, y=75.00, z=36.09], EntityPig['Pig'/4117, l='MpServer', x=-106.50, y=75.00, z=34.78], EntityPig['Pig'/4118, l='MpServer', x=-107.50, y=76.00, z=38.50], EntityItem['item.tile.flower1.dandelion'/4119, l='MpServer', x=-56.38, y=72.13, z=44.34], EntityChicken['Chicken'/4120, l='MpServer', x=-73.50, y=74.00, z=38.50], EntityChicken['Chicken'/4121, l='MpServer', x=-76.50, y=75.00, z=39.50], EntityChicken['Chicken'/4122, l='MpServer', x=-75.50, y=75.00, z=38.50], EntityChicken['Chicken'/4123, l='MpServer', x=-79.50, y=75.00, z=39.50], EntityZombie['Zombie'/5148, l='MpServer', x=-64.50, y=15.00, z=36.50], EntityCow['Cow'/3100, l='MpServer', x=31.31, y=65.00, z=105.53], EntityZombie['Zombie'/5164, l='MpServer', x=-90.69, y=36.00, z=109.63], EntityCreeper['Creeper'/5172, l='MpServer', x=-100.03, y=58.00, z=7.38], EntitySkeleton['Skeleton'/5173, l='MpServer', x=-59.50, y=24.00, z=-7.50], EntityZombie['Zombie'/5174, l='MpServer', x=-93.03, y=36.00, z=107.53], EntityZombie['Zombie'/5175, l='MpServer', x=-82.50, y=36.00, z=110.50], EntityZombie['Zombie'/5191, l='MpServer', x=-92.50, y=58.00, z=11.50], EntityCreeper['Creeper'/5192, l='MpServer', x=-91.50, y=58.00, z=7.56], EntityCreeper['Creeper'/5193, l='MpServer', x=-89.50, y=58.00, z=8.50], EntityBat['Bat'/5206, l='MpServer', x=-35.56, y=43.71, z=-3.35], EntityBat['Bat'/5207, l='MpServer', x=-69.45, y=24.74, z=23.42], EntityCow['Cow'/3192, l='MpServer', x=-4.50, y=64.00, z=115.50], EntityChicken['Chicken'/4230, l='MpServer', x=-26.50, y=76.00, z=62.50], EntityChicken['Chicken'/4231, l='MpServer', x=-26.50, y=77.00, z=61.50], EntityChicken['Chicken'/4232, l='MpServer', x=-26.50, y=77.00, z=61.50], EntityChicken['Chicken'/4233, l='MpServer', x=-20.24, y=70.00, z=63.38], EntityChicken['Chicken'/4246, l='MpServer', x=-61.53, y=77.00, z=70.31], EntityChicken['Chicken'/4247, l='MpServer', x=-75.47, y=77.00, z=62.50], EntityChicken['Chicken'/4248, l='MpServer', x=-68.53, y=76.00, z=67.63], EntityChicken['Chicken'/4249, l='MpServer', x=-70.50, y=75.00, z=66.50], EntitySkeleton['Skeleton'/5285, l='MpServer', x=-60.50, y=24.00, z=-6.50], EntitySkeleton['Skeleton'/5286, l='MpServer', x=34.50, y=34.00, z=69.50], EntityEnderman['Enderman'/5287, l='MpServer', x=-97.88, y=50.00, z=-11.41], EntityCreeper['Creeper'/5295, l='MpServer', x=6.00, y=19.00, z=120.59], EntityZombie['Zombie'/5297, l='MpServer', x=9.50, y=18.00, z=123.50], EntitySkeleton['Skeleton'/5306, l='MpServer', x=33.50, y=34.00, z=67.50], EntitySkeleton['Skeleton'/5322, l='MpServer', x=-24.50, y=56.00, z=30.91], EntityCreeper['Creeper'/5323, l='MpServer', x=-30.50, y=54.00, z=34.50], EntityChicken['Chicken'/4300, l='MpServer', x=-101.50, y=79.00, z=65.50], EntityChicken['Chicken'/4301, l='MpServer', x=-101.50, y=79.00, z=64.50], EntityChicken['Chicken'/4302, l='MpServer', x=-101.50, y=79.00, z=64.50], EntityChicken['Chicken'/4303, l='MpServer', x=-100.50, y=79.00, z=64.50], EntitySkeleton['Skeleton'/5327, l='MpServer', x=-28.50, y=54.00, z=35.50], EntitySkeleton['Skeleton'/5328, l='MpServer', x=-31.50, y=54.00, z=34.50], EntityCreeper['Creeper'/5330, l='MpServer', x=-34.50, y=57.00, z=5.50], EntitySkeleton['Skeleton'/5334, l='MpServer', x=-104.50, y=19.00, z=-7.50], EntityCreeper['Creeper'/5346, l='MpServer', x=-37.50, y=23.00, z=22.50], EntitySkeleton['Skeleton'/5349, l='MpServer', x=-103.50, y=19.00, z=-8.50], EntityCow['Cow'/3311, l='MpServer', x=-5.50, y=67.00, z=111.50], EntityCow['Cow'/3312, l='MpServer', x=-2.50, y=67.00, z=111.50], EntityCow['Cow'/3313, l='MpServer', x=-5.50, y=67.00, z=109.50], EntityBat['Bat'/5434, l='MpServer', x=-55.10, y=15.00, z=-27.25], EntityBat['Bat'/5435, l='MpServer', x=-55.11, y=15.00, z=-25.63], EntitySkeleton['Skeleton'/5447, l='MpServer', x=-37.50, y=23.00, z=23.50], EntityCreeper['Creeper'/5448, l='MpServer', x=-68.50, y=42.00, z=0.50], EntityBat['Bat'/5455, l='MpServer', x=13.94, y=39.00, z=96.69], EntityBat['Bat'/5456, l='MpServer', x=15.75, y=39.00, z=95.25], EntityBat['Bat'/5459, l='MpServer', x=-3.69, y=36.00, z=121.75], EntityChicken['Chicken'/3438, l='MpServer', x=-8.31, y=69.00, z=91.34], EntityChicken['Chicken'/3439, l='MpServer', x=-11.50, y=69.00, z=92.50], EntitySkeleton['Skeleton'/5487, l='MpServer', x=-57.50, y=20.00, z=-30.50], EntityChicken['Chicken'/3440, l='MpServer', x=-8.56, y=69.00, z=89.59], EntityChicken['Chicken'/3441, l='MpServer', x=-13.50, y=69.00, z=90.50], EntitySpider['Spider'/4481, l='MpServer', x=-99.50, y=16.00, z=101.13], EntitySkeleton['Skeleton'/4503, l='MpServer', x=-62.50, y=23.00, z=127.50], EntitySkeleton['Skeleton'/5527, l='MpServer', x=-69.50, y=15.00, z=102.50], EntityEnderman['Enderman'/5528, l='MpServer', x=-3.50, y=53.00, z=-8.50], EntitySkeleton['Skeleton'/5532, l='MpServer', x=-69.50, y=15.00, z=100.50], EntitySkeleton['Skeleton'/5533, l='MpServer', x=-68.50, y=15.00, z=100.50], EntityCreeper['Creeper'/4514, l='MpServer', x=-46.50, y=32.00, z=94.50], EntityBat['Bat'/4543, l='MpServer', x=-87.38, y=17.71, z=105.66], EntitySheep['Sheep'/4544, l='MpServer', x=30.50, y=63.00, z=37.50], EntityZombie['Zombie'/4547, l='MpServer', x=-60.50, y=23.00, z=126.50], EntityChicken['Chicken'/4619, l='MpServer', x=-90.50, y=78.00, z=16.50], EntityChicken['Chicken'/4620, l='MpServer', x=-90.50, y=77.00, z=15.50], EntityChicken['Chicken'/4621, l='MpServer', x=-90.63, y=76.00, z=13.53], EntityChicken['Chicken'/4622, l='MpServer', x=-92.50, y=76.00, z=15.50], EntityZombie['Zombie'/4643, l='MpServer', x=-84.50, y=36.00, z=110.50], EntityZombie['Zombie'/4644, l='MpServer', x=-83.50, y=36.00, z=109.50], EntityZombie['Zombie'/4645, l='MpServer', x=-92.41, y=36.00, z=96.00], EntityZombie['Zombie'/4653, l='MpServer', x=-74.50, y=17.00, z=110.50], EntitySkeleton['Skeleton'/4682, l='MpServer', x=-64.50, y=48.00, z=56.50], EntityClientPlayerMP['ENDERMANYK'/503, l='MpServer', x=-30.64, y=78.62, z=47.60], EntitySquid['Squid'/4747, l='MpServer', x=-43.51, y=56.36, z=87.51], EntitySquid['Squid'/4762, l='MpServer', x=-33.72, y=62.47, z=82.88], EntitySquid['Squid'/4763, l='MpServer', x=-36.71, y=60.83, z=88.36], EntityZombie['Zombie'/4791, l='MpServer', x=-104.66, y=19.00, z=93.50], EntitySkeleton['Skeleton'/4798, l='MpServer', x=-96.97, y=17.00, z=95.50], EntityZombie['Zombie'/4799, l='MpServer', x=-95.44, y=15.00, z=103.44], EntityZombie['Zombie'/4800, l='MpServer', x=-107.50, y=19.00, z=95.50], EntitySpider['Spider'/4846, l='MpServer', x=-70.50, y=15.00, z=105.50], EntityCow['Cow'/4859, l='MpServer', x=36.22, y=66.00, z=104.28], EntityCow['Cow'/4860, l='MpServer', x=36.47, y=66.00, z=107.66], EntityPig['Pig'/4861, l='MpServer', x=47.50, y=69.00, z=110.50], EntityPig['Pig'/4862, l='MpServer', x=46.50, y=68.00, z=110.50], EntityCow['Cow'/4863, l='MpServer', x=39.72, y=68.00, z=107.47], EntitySquid['Squid'/4865, l='MpServer', x=-33.14, y=58.25, z=87.10], EntitySkeleton['Skeleton'/4876, l='MpServer', x=-91.50, y=26.00, z=107.50], EntityCreeper['Creeper'/4895, l='MpServer', x=-109.50, y=58.00, z=34.50], EntitySquid['Squid'/4909, l='MpServer', x=-43.53, y=56.00, z=90.35], EntitySquid['Squid'/4910, l='MpServer', x=-42.53, y=56.00, z=95.23], EntitySquid['Squid'/4911, l='MpServer', x=-43.53, y=56.00, z=88.33], EntitySquid['Squid'/4912, l='MpServer', x=-41.10, y=56.00, z=91.08], EntitySheep['Sheep'/4923, l='MpServer', x=-92.78, y=73.00, z=-9.50], EntitySheep['Sheep'/4924, l='MpServer', x=-91.19, y=73.00, z=-9.50], EntitySheep['Sheep'/4925, l='MpServer', x=-95.22, y=72.00, z=-12.50], EntitySheep['Sheep'/4926, l='MpServer', x=-96.53, y=73.00, z=-12.50], EntityItem['item.item.seeds'/4927, l='MpServer', x=3.16, y=64.13, z=-5.16], EntityEnderman['Enderman'/4967, l='MpServer', x=-92.00, y=58.00, z=10.22], EntitySheep['Sheep'/4981, l='MpServer', x=-85.50, y=67.00, z=-26.50], EntitySheep['Sheep'/4982, l='MpServer', x=-82.50, y=64.00, z=-29.50], EntitySheep['Sheep'/4983, l='MpServer', x=-79.50, y=60.00, z=-31.50], EntitySheep['Sheep'/4984, l='MpServer', x=-79.50, y=64.00, z=-29.50], EntityPig['Pig'/5110, l='MpServer', x=44.84, y=68.00, z=118.44], EntityPig['Pig'/5111, l='MpServer', x=35.16, y=66.00, z=112.38]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 469280032 bytes (447 MB) / 1107296256 bytes (1056 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -Xms1024m -Xmx4096m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_E7 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	Launched Version: 1.7.10
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [vanilla]
	Current Language: English (US)
	Profiler Position: root.gameRenderer.level.sky
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Adam0530** [comment]
Have you tried the latest action build?

**Comment by ENDERMANYK** [comment]
> Have you tried the latest action build?

Already, The crash is different from the before 1.12.2 crash, so idk is optifine problem or my code problem..

**Comment by Zeyrox1090** [comment]
is the shader laggy
??

**Comment by ENDERMANYK** [comment]
> is the shader laggy
> ??

Depand on devices, if you can get 100~200 FPS with optifine then it's ok for your device

**Comment by Adam0530** [comment]
> > is the shader laggy
> > ??
> 
> Depand on devices, if you can get 100~200 FPS with optifine then it's ok for your device

Did the shader crash when you just start picking the shader after load to some world or it will crash after a minute using a shader when just load to some world?

**Comment by Zeyrox1090** [comment]
> > is the shader laggy
> > ??
> 
> Depand on devices, if you can get 100~200 FPS with optifine then it's ok for your device

lol can i test the shader?
to see if it works

**Comment by khanhduytran0** [comment]
Again missing functions..

**Comment by Zeyrox1090** [comment]
i wanna use his shader lol

**Comment by ENDERMANYK** [comment]
Idk if your guys fix this problem, i am using the latest version in the actions and it still crash, the crashlog is still the same

**Comment by Adam0530** [comment]
> Idk if your guys fix this problem, i am using the latest version in the actions and it still crash, the crashlog is still the same 

I am asking you this.. Pls answer this one.. And if you answer this one maybe I can help you

**Comment by ENDERMANYK** [comment]
> > Idk if your guys fix this problem, i am using the latest version in the actions and it still crash, the crashlog is still the same
> 
> I am asking you this.. Pls answer this one.. And if you answer this one maybe I can help you

Oh shader will crash when you join the world and select it

**Comment by Adam0530** [comment]
> > > Idk if your guys fix this problem, i am using the latest version in the actions and it still crash, the crashlog is still the same
> > 
> > I am asking you this.. Pls answer this one.. And if you answer this one maybe I can help you
> 
> Oh shader will crash when you join the world and select it

What version of minecraft you use? Forge with optifine or optifine only?

**Comment by ENDERMANYK** [comment]
> > > > Idk if your guys fix this problem, i am using the latest version in the actions and it still crash, the crashlog is still the same
> > > 
> > > 
> > > I am asking you this.. Pls answer this one.. And if you answer this one maybe I can help you
> > 
> > 
> > Oh shader will crash when you join the world and select it
> 
> What version of minecraft you use? Forge with optifine or optifine only?

Err, version is already on the title, both crashes

**Comment by Adam0530** [comment]
> > > > > Idk if your guys fix this problem, i am using the latest version in the actions and it still crash, the crashlog is still the same
> > > > 
> > > > 
> > > > I am asking you this.. Pls answer this one.. And if you answer this one maybe I can help you
> > > 
> > > 
> > > Oh shader will crash when you join the world and select it
> > 
> > What version of minecraft you use? Forge with optifine or optifine only?
> 
> Err, version is already on the title, both crashes

Lol... When I said "which version" I mean optifine only or forge with optifine.. And yeah.. Idk about your problem.. Mine was fine... I am only using optifine and it work.. If necessary, can you send the shader and I will test it out with my phone.. Maybe the shader crash because of your device or something

**Comment by ENDERMANYK** [comment]
> > > > > > Idk if your guys fix this problem, i am using the latest version in the actions and it still crash, the crashlog is still the same
> > > > > 
> > > > > 
> > > > > I am asking you this.. Pls answer this one.. And if you answer this one maybe I can help you
> > > > 
> > > > 
> > > > Oh shader will crash when you join the world and select it
> > > 
> > > 
> > > What version of minecraft you use? Forge with optifine or optifine only?
> > 
> > 
> > Err, version is already on the title, both crashes
> 
> Lol... When I said "which version" I mean optifine only or forge with optifine.. And yeah.. Idk about your problem.. Mine was fine... I am only using optifine and it work.. If necessary, can you send the shader and I will test it out with my phone.. Maybe the shader crash because of your device or something

Well , there are already six people test the shader on three different processors and all of them crash, most important thing is the forge,fabric and optifine works fine on my phone, it only crash when i applied shader on 1.7.10, 1.12.2~1.16.5 works fine

**Comment by khanhduytran0** [comment]
I undone 2d35c59 since it cause more buggy on some versions. I will look at this then

**Comment by Adam0530** [comment]
> > > > > > > Idk if your guys fix this problem, i am using the latest version in the actions and it still crash, the crashlog is still the same
> > > > > > 
> > > > > > 
> > > > > > I am asking you this.. Pls answer this one.. And if you answer this one maybe I can help you
> > > > > 
> > > > > 
> > > > > Oh shader will crash when you join the world and select it
> > > > 
> > > > 
> > > > What version of minecraft you use? Forge with optifine or optifine only?
> > > 
> > > 
> > > Err, version is already on the title, both crashes
> > 
> > Lol... When I said "which version" I mean optifine only or forge with optifine.. And yeah.. Idk about your problem.. Mine was fine... I am only using optifine and it work.. If necessary, can you send the shader and I will test it out with my phone.. Maybe the shader crash because of your device or something
> 
> Well , there are already six people test the shader on three different processors and all of them crash, most important thing is the forge,fabric and optifine works fine on my phone, it only crash when i applied shader on 1.7.10, 1.12.2~1.16.5 works fine

Well, can I ask about how you install a new update of pojavlauncher? Like reinstall or just installing it without reinstall.. If you just install it without deleting the app.. You must choose the app debug no runtime and not app bebug.. and it still did not work It is recommend for you to reinstall.. And if it still did not work that mean pojav did not support your shader or your code just wrong.. Sorry for bas english lol.. I am still learning

**Comment by ENDERMANYK** [comment]
> I undone [2d35c59](https://github.com/PojavLauncherTeam/PojavLauncher/commit/2d35c59b91097b8236aaaa1d4f69e5ab24379dd1) since it cause more buggy on some versions. I will look at this then

Ok thanks, i mainly play on 1.16 version so nothing wrong with me , but some testers still love playing on 1.7.10, so..

**Comment by LuisReyes234723** [comment]
Quisiera saber la solucion 
Cuando lo activo en la 1.12.2 es normal sin crash
Pero cuando lo activo en la 1.7.10 me crashea y ya intente de todo yo quisiera saber la solucion a mi me gustan los mods de esa version🥺me dirian que puedo hacer🥺

**Comment by 1493028** [comment]
Minecraft 1.7.10 I sometimes crash when I play it for about 10-20 minutes it crashes and there is no crash log

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build build
